name: Prowler - Azure security scan

on:
  # Run on demand and every work-night at 02:00 UTC (≈ 12 pm AEST, adjust to taste)
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1-5'

# GitHub must be allowed to mint an ID-token for OIDC
permissions:
  id-token: write
  contents: read

jobs:
  prowler-azure:
    runs-on: ubuntu-latest

    steps:
      # OIDC login – requires a Service Principal with a federated-credential
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id:      ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:      ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Install the CLI
      - name: Install Prowler
        run: |
          python -m pip install --upgrade pip
          pip install prowler

      # Run the scan.  --az-cli-auth tells Prowler to use the token the
      # azure/login step has already placed in the AZ CLI credential store.
      - name: Run Prowler
        run: |
          prowler azure \
            --az-cli-auth \
            --subscription-ids "${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            --output-formats html \
            --compliance cis_3.0_azure \
            --output-directory ./prowler-output \
            --ignore-exit-code-3

      # Keep the results
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: prowler-azure-report
          path: ./prowler-output
